image:
- Visual Studio 2017
- Ubuntu

stack: python 3

environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  PY_DIR: C:\Python37-x64

clone_depth: 3

build: off

init:
- cmd: set PATH=%MINGW_DIR%;%PATH%
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:
- pip install -e .[tests]

test_script: pytest -rsv

