notifications:
  email: false

git:
  depth: 3
  
python:
    - 2.7
    - 3.5
  
os:
    - osx
    - linux

addons:
    apt:
      packages:
        - gfortran

install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh
      else 
        wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
      fi
      
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - hash -r
    
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - pip -q install coveralls
    - python setup.py develop

script:
    - coverage run tests/test.py -v

after_success:
    - coveralls

