language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python:
- 3.7
- 3.6

addons:
  apt:
    packages:
    - gfortran

matrix:
  include:
  - os: linux
    python: 3.7
    install: pip install -e .[tests,cov]
    script:
    - flake8
    - mypy .
    after_success:
    - pytest --cov
    - coveralls
  - os: osx
    language: minimal
    before_install: brew install gcc > /dev/null
    install: pip3 install -e .[tests]
#  - os: windows
#    language: minimal
#    before_install:
#    - choco install python3
#    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"


install: pip install -e .[tests]

script: pytest -rsv


